config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  
  root 'home#index'
  
  resources :accounts
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :user
    
    validates :user, presence: true
    validates :name, presence: true
    validates :description, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  
  has_many :accounts 
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_action :require_login
    
    def index
        @account = Account.new
        @accounts = current_user.accounts
    end
    
    def show
        @account = current_user.accounts.find(params[:id])
    end
    
    def new
        @account = current_user.accounts.build
    end
    
    def create
        @account = current_user.accounts.build(account_params)
        
        if @account.save
            redirect_to account_path(@account)
        end
    end
    
    def edit
        @account = current_user.accounts.find(params[:id])
    end
    
    def update
        @account = current_user.accounts.find(params[:id])
        
        if @account.update(account_params)
            redirect_to @account
        else
            render 'edit'
        end
    end
    
    def destroy
        @account = current_user.accounts.find(params[:id])
        @account.destroy
        redirect_to accounts_path
    end
    
    private
    def account_params
        params.require(:account).permit(:name, :description)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
   def show
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_form.html.erb
<div class="row">
      <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-primary">
                  <div class="panel-heading">Direct Deposit</div>
                  <div class="panel-body">
                  <%= simple_form_for @account do |f| %>
                        <%= f.input :name %>
                        <%= f.input :description %>

                        <%= f.button :submit, class: 'btn btn-success' %>
                  <% end %> 
                  </div>
            </div>
      </div>
</div>

app/views/accounts/edit.html.erb
<div id="clearance" class="sign-up">
  <div class="row">
      <div class="col-md-4 col-md-offset-4">
          <h3>Editing Transaction</h3>
            <div class="panel panel-primary">
                  <div class="panel-heading">Transaction</div>
                  <div class="panel-body">
                    <%= simple_form_for @account do |f| %>
                          <%= f.input :name %>
                          <%= f.input :description %>
                          
                          <%= f.button :submit, class: 'btn btn-success' %>
                    <% end %> 
                  </div>
            </div>
            <%= link_to 'Back', account_path, class: 'btn btn-primary btn-sm' %>
      </div>
</div>

app/views/accounts/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    
      <ul class="nav navbar-nav navbar-left">
        <li><a href="/accounts/new">Deposit</a></li>
        <li><a href="/accounts/new">Withdraw</a></li>
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/sign_out">Logout</a></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
   <div class="row">
   <a href="http://imgur.com/lIKAwKg"><img src="http://i.imgur.com/lIKAwKg.jpg" title="source: imgur.com" width=100% height=100%/></a>
   </div>
</div>

<div class="row"></div>

<div class="col-md-2">
</div>

<div class="row">
<div class="media">
 <div class="media-body">

  <div class="col-md-9">
    <table class="table table-striped table-striped">
       
    <thead>
      <tr>
        <th>Options</th>
        <th>Type</th>
        <th></th>
        <th></th>
        <th>Amount</th>
        <th></th>
      </tr>
    </thead>
    
    <tbody>
      <% @accounts.each do |account| %>
        <tr>
            <td>
              <div class="btn-group">
                <%= link_to ' Show ', account_path(account), class: 'btn btn-success btn-sm' %>
                <%= link_to ' Edit ', edit_account_path(account), class: 'btn btn-success btn-sm' %>
                <%= link_to 'Delete', account_path(account), method: :delete, class: 'btn btn-success btn-sm' %>
              </div>
            </td>
            <td><%= account.name %></td>
            <td></td>
            <td></td>
            <td><%= account.description %></td>
            <td></td>
          
        </tr>
      <% end %>
    </tbody>
  </table>
 </div>

</div>
</div>
</div>

app/views/accounts/new.html.erb
<div class="row">
      <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-primary">
                  <div class="panel-heading">Direct Deposit</div>
                  <div class="panel-body">
                  <%= simple_form_for @account do |f| %>
                        <%= f.input :name %>
                        <%= f.input :description %>
      
                        <%= f.button :submit, class: 'btn btn-success' %>
                  <% end %> 
                  </div>
            </div>
      </div>
</div>

app/views/accounts/show.html.erb
<div class="row">
    <h1></h1>
    <div class="col-md-4 col-md-offset-4">
        <button class="btn btn-primary btn-lg btn-block"><%= @account.name %></button>
        <button class="btn btn-default btn-lg btn-block"><%= @account.description %></button>
        <h3></h3>
            <div class = "col-md-3"></div>
            <div class="btn-group">
                <%= link_to 'Back', accounts_path, class: 'btn btn-info btn' %>
                <%= link_to 'Edit', edit_account_path(@account), class: 'btn btn-info btn' %>
                <%= link_to 'Delete', account_path(@account), method: :delete, class: 'btn btn-info btn' %>
            </div>
    </div>
</div>

app/views/home/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">About</a></li>
        <li><a href="/sign_in">Login</a></li>
        <li><a href="/sign_up">Sign Up</a></li>
        
      </ul>

      <% if signed_in? %>
        Signed in as: <%= current_user.email %>
        <%= button_to 'Sign out', sign_out_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign in', sign_in_path %>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<a href="http://imgur.com/KB4YBdf"><img src="http://i.imgur.com/KB4YBdf.png" title="source: imgur.com" width=100% height=100% /></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
  </head>

  <body>
    
    <section>
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>
      <%= yield %>
    </section>
  
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <div class="row">
      <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-primary">
                  <div class="panel-heading">Create Account</div>
                  <div class="panel-body">
                    <%= simple_form_for @user do |f| %>
                          <%= f.input :email %>
                          <%= f.input :password %>
        
                          <%= f.button :submit, class: 'btn btn-success' %>
                    <% end %> 
                  </div>
            </div> 
      </div>
</div>

app/views/welcome/show.html.erb
<h1>Welcome</h1>